### ISSUE TITLE
Adapters models

### ISSUE THREAD

**Issue by dadelani** [cambridgeltl/composable-sft#1]
Hi,

Really nice work. Everything seems to work fine. 

I'm wondering if you plan to release the Adapters models (based on MAD-X) too for comparison. I understand that this is focused on SFT, it would be nice to also have the Adapters.

**Comment by AlanAnsell** [comment]
Hi David, thanks for the positive feedback! I won't be releasing the adapters as part of this repo, but I'd be happy to pass them on to you or anyone else who's interested, please email me at "aja63 at cam dot ac dot uk".

**Comment by dadelani** [comment]
Thank you for the response. I will send an email
